# Generated by Django 3.2.4 on 2021-06-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='promo_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
