# Generated by Django 3.2.4 on 2021-06-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('soon', 'soon'), ('in process', 'in process'), ('closed', 'closed')], default='soon', max_length=20)),
                ('result', models.CharField(choices=[('team_a', 'team_a'), ('team_b', 'team_b')], max_length=20)),
                ('date', models.DateTimeField()),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_a', to='MatchTeam.team')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_b', to='MatchTeam.team')),
            ],
        ),
    ]
